### Admin Login
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@kindergarten.com",
  "password": "password"
}

### Get Auth Token
@authToken = {{login.response.body.token}}

### Get All Students
GET http://localhost:3000/api/students
Authorization: Bearer {{authToken}}

### Get Student by ID
GET http://localhost:3000/api/students/1
Authorization: Bearer {{authToken}}

### Get Another Student
GET http://localhost:3000/api/students/2
Authorization: Bearer {{authToken}} 