# @name Token
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@jardin.com",
  "password": "password"
}


###
@authToken = {{Token.response.body.token}}

### Obtener Directivos

GET http://localhost:3000/api/directivos
Authorization: Bearer {{authToken}}


### Crear Directivo (cuando se implemente)
POST http://localhost:3000/api/directivos
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nombre": "María",
  "apellido": "Rodríguez",
  "email": "maria.rodriguez@jardin.com",
  "password": "password123",
  "telefono": "11-1111-2222",
  "cargo": "Directora"
} 