### Obtener Asistencia de Hoy
GET http://localhost:3000/api/asistencia?fecha=2024-01-15
Authorization: Bearer {{authToken}}

### Obtener Asistencia por Sala
GET http://localhost:3000/api/asistencia?sala=Sala de 3
Authorization: Bearer {{authToken}}

### Obtener Asistencia de un Alumno
GET http://localhost:3000/api/asistencia?alumno_id=1
Authorization: Bearer {{authToken}}

### Obtener Todas las Asistencias
GET http://localhost:3000/api/asistencia
Authorization: Bearer {{authToken}} 