### Login de Administrador
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@jardin.com",
  "password": "password"
}

### Login de Maestra (cuando se cree)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "maestra@jardin.com",
  "password": "password"
}

### Verificar Token
GET http://localhost:3000/api/auth/verificar
Authorization: Bearer {{authToken}} 