### Admin Login
#@name login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin1234"
}

### Teacher Login (when created)
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "teacher@kindergarten.com",
  "password": "password"
}

### Verify Token
GET http://localhost:3001/api/auth/verify
Authorization: Bearer {{authToken}} 
